### ISSUE TITLE
Launching this repo

### ISSUE THREAD

**Issue by danielbachhuber** [pantheon-systems/pantheon-wordpress-develop#1]
- [x] Transfer to Pantheon organization
- [x] Enable Circle on Pantheon organization to follow this project; set up appropriate env variables
- [x] Create a new Pantheon user, and use their machine token in Circle config
- [x] Post build status to Slack
- [x] Trigger builds on a nightly basis somehow: https://github.com/pantheon-systems/pantheon-wordpress-develop/issues/2

**Comment by stevector** [comment]
@bmackinney Can you set up the Slack integration here? https://circleci.com/gh/pantheon-systems/pantheon-wordpress-develop/edit#hooks

I do not have the Slack permissions to do so. We'd like build results to post into the wordpress slack channel.

**Comment by stevector** [comment]
Slack notification is happening too. Closing this issue.
