### ISSUE TITLE
Trigger builds on a nightly basis

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/pantheon-wordpress-develop#2]
We can trigger nightly builds on circle CI following the step here: https://circleci.com/docs/nightly-builds/

Summary with slight changes:

Step 1: Make file: trigger-circle-ci-build-by-repo-and-branch.sh 

``` sh
#!/bin/bash
# This file triggers a build of a branch on Circle CI.
# It was copied and simplified from https://circleci.com/docs/nightly-builds/

# Example value: pantheon-systems/pantheon-wordpress-develop
_project=$1
# Example value: master
_branch=$2
# Example value: q1w2e3r4t5y6
# Generate CircleCI token here https://circleci.com/account/api
_circle_token=$3

trigger_build_url=https://circleci.com/api/v1/project/${_project}/tree/${_branch}?circle-token=${_circle_token}

curl \
--header "Accept: application/json" \
--header "Content-Type: application/json" \
--request POST ${trigger_build_url}
```

Step 2: Trigger script with `./trigger-circle-ci-build-by-repo-and-branch.sh pantheon-systems/pantheon-wordpress-develop  master ${CIRCLE_TOKEN}`

Step 3. Trigger on nightly cron, possibly

```
30 0 * * * /bin/bash /home/ubuntu/bin/trigger-circle-ci-build-by-repo-and-branch.sh pantheon-systems/pantheon-wordpress-develop  master$(cat /home/ubuntu/.circle_token) 2>&1 | /usr/bin/logger
```

**Comment by stevector** [comment]
@joshkoenig Is our internal Jenkins instance the best place to do this triggering of nightly builds of wordpress.org changes?

**Comment by joshkoenig** [comment]
It certainly could be. Can you make the case to @nstielau and see what he says?

**Comment by danielbachhuber** [comment]
@stevector On this note, Can you disable automatic triggering of builds on this repo, so I can easily edit the README without triggering a bunch of notifications?

**Comment by stevector** [comment]
@danielbachhuber, the building is stopped. @joshkoenig yes, I'll find time to talk with @nstielau.

**Comment by stevector** [comment]
Since we are looking to divest in our internal Jenkins instance I've signed up for a cron-as-a-service to curl this URL. We are adding more and more circle.yml files to public repos that will benefit from this running, I'll manage the triggering of nightly Circle builds there. I'll close this issue tomorrow after seeing the nightly build be triggered.

**Comment by stevector** [comment]
The cron ran overnight
