### ISSUE TITLE
Custom notifications to Slack

### ISSUE THREAD

**Issue by danielbachhuber** [pantheon-systems/pantheon-wordpress-develop#4]
Circle's default Slack notifications aren't very helpful in our context:

![image](https://cloud.githubusercontent.com/assets/36432/16243956/9c0067b0-37ae-11e6-875f-e5b6c51b33eb.png)

It would be cool if we could indicate whether or not the build failed, and then the stats that PHPUnit reports about the test suite (# passed, #skipped, # failed)

**Comment by stevector** [comment]
Doesn't the word "success" and the green stripe indicate a pass?

**Comment by danielbachhuber** [comment]
> Doesn't the word "success" and the green stripe indicate a pass?

It does, but doesn't indicate any of the context for the pass. In this case, it's more helpful to know the WordPress changeset tested, and how many tests passed / were skipped.

I have something in mind if you want me to put it together.

**Comment by stevector** [comment]
Sure, I imagine we could use the `notify` stage of CircleCI to do a custom notification.

**Comment by danielbachhuber** [comment]
@aaronjorbin are you aware of any way to produce a summary of the PHPUnit test that [isn't this XML or JSON](https://phpunit.de/manual/current/en/logging.html) ?

**Comment by danielbachhuber** [comment]
@stevector Did someone disable the Circle Slack notifications? What's place for this reporting?

**Comment by stevector** [comment]
@danielbachhuber It is still reporting in the WordPress channel. Nightly runs were not occurring over the weekend. The cron as a service stopped running when the trial period expired. I've now converted it to a paid plan.
